export const FETCH_ALL_RIDES = "FETCH_ALL_RIDES";
export const FETCH_ALL_RIDES_SUCCESS = "FETCH_ALL_RIDES_SUCCESS";
export const FETCH_ALL_RIDES_FAILED = "FETCH_ALL_RIDES_FAILED";
export const FETCH_ALL_RIDES_PENDING = "FETCH_ALL_RIDES_PENDING";

export const FETCH_ONE_RIDES = "FETCH_ONE_RIDES";
export const FETCH_ONE_RIDES_SUCCESS = "FETCH_ONE_RIDES_SUCCESS";
export const FETCH_ONE_RIDES_FAILED = "FETCH_ONE_RIDES_FAILED";
export const FETCH_ONE_RIDES_PENDING = "FETCH_ONE_RIDES_PENDING";

export const ADD_RIDES = "ADD_RIDES";
export const ADD_RIDES_SUCCESS = "ADD_RIDES_SUCCESS";
export const ADD_RIDES_FAILED = "ADD_RIDES_FAILED";
export const ADD_RIDES_PENDING = "ADD_RIDES_PENDING";

export const REMOVE_RIDES = "REMOVE_RIDES";
export const REMOVE_RIDES_SUCCESS = "REMOVE_RIDES_SUCCESS";
export const REMOVE_RIDES_FAILED = "REMOVE_RIDES_FAILED";
export const REMOVE_RIDES_PENDING = "REMOVE_RIDES_PENDING";

export const BASE_URL = `http://localhost:8000/rides/`;
