export const FETCH_ALL_PASSENGERS = "FETCH_ALL_PASSENGERS";
export const FETCH_ALL_PASSENGERS_SUCCESS = "FETCH_ALL_PASSENGERS_SUCCESS";
export const FETCH_ALL_PASSENGERS_FAILED = "FETCH_ALL_PASSENGERS_FAILED";
export const FETCH_ALL_PASSENGERS_PENDING = "FETCH_ALL_PASSENGERS_PENDING";

export const FETCH_ONE_PASSENGERS = "FETCH_ONE_PASSENGERS";
export const FETCH_ONE_PASSENGERS_SUCCESS = "FETCH_ONE_PASSENGERS_SUCCESS";
export const FETCH_ONE_PASSENGERS_FAILED = "FETCH_ONE_PASSENGERS_FAILED";
export const FETCH_ONE_PASSENGERS_PENDING = "FETCH_ONE_PASSENGERS_PENDING";

export const ADD_PASSENGERS = "ADD_PASSENGERS";
export const ADD_PASSENGERS_SUCCESS = "ADD_PASSENGERS_SUCCESS";
export const ADD_PASSENGERS_FAILED = "ADD_PASSENGERS_FAILED";
export const ADD_PASSENGERS_PENDING = "ADD_PASSENGERS_PENDING";

export const REMOVE_PASSENGERS = "REMOVE_PASSENGERS";
export const REMOVE_PASSENGERS_SUCCESS = "REMOVE_PASSENGERS_SUCCESS";
export const REMOVE_PASSENGERS_FAILED = "REMOVE_PASSENGERS_FAILED";
export const REMOVE_PASSENGERS_PENDING = "REMOVE_PASSENGERS_PENDING";

export const BASE_URL = `http://localhost:8001/passengers/`;
