export const FETCH_ALL_DRIVERS = "FETCH_ALL_DRIVERS";
export const FETCH_ALL_DRIVERS_SUCCESS = "FETCH_ALL_DRIVERS_SUCCESS";
export const FETCH_ALL_DRIVERS_FAILED = "FETCH_ALL_DRIVERS_FAILED";
export const FETCH_ALL_DRIVERS_PENDING = "FETCH_ALL_DRIVERS_PENDING";

export const FETCH_ONE_DRIVERS = "FETCH_ONE_DRIVERS";
export const FETCH_ONE_DRIVERS_SUCCESS = "FETCH_ONE_DRIVERS_SUCCESS";
export const FETCH_ONE_DRIVERS_FAILED = "FETCH_ONE_DRIVERS_FAILED";
export const FETCH_ONE_DRIVERS_PENDING = "FETCH_ONE_DRIVERS_PENDING";

export const ADD_DRIVERS = "ADD_DRIVERS";
export const ADD_DRIVERS_SUCCESS = "ADD_DRIVERS_SUCCESS";
export const ADD_DRIVERS_FAILED = "ADD_DRIVERS_FAILED";
export const ADD_DRIVERS_PENDING = "ADD_DRIVERS_PENDING";

export const REMOVE_DRIVERS = "REMOVE_DRIVERS";
export const REMOVE_DRIVERS_SUCCESS = "REMOVE_DRIVERS_SUCCESS";
export const REMOVE_DRIVERS_FAILED = "REMOVE_DRIVERS_FAILED";
export const REMOVE_DRIVERS_PENDING = "REMOVE_DRIVERS_PENDING";

export const BASE_URL = `http://localhost:8001/drivers/`;
